services:
  - type: web
    name: kazay-website
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 